# ==========================================
# SolarNexum OS - Source Manifest
# ==========================================

SOLARNEXUM_VERSION="0.1"
LFS_REFERENCE="13.1-systemd"

# Toolchain principal
BINUTILS_VERSION="2.47"
GCC_VERSION="16.2.0"
GLIBC_VERSION="2.44"

# Kernel
LINUX_VERSION="7.1.8"

# Sistema de inicializacao
SYSTEMD_VERSION="261.2"

# Ferramentas fundamentais
COREUTILS_VERSION="9.11"
MAKE_VERSION="4.4.1"
BASH_VERSION="5.3"
TAR_VERSION="1.35"
XZ_VERSION="5.8.3"

# Arquitetura
TARGET_ARCH="x86_64"