# ==========================================
# SolarNexum OS - Source Manifest
# LFS 13.1-systemd
# ==========================================

SOLARNEXUM_VERSION="0.1"
LFS_REFERENCE="13.1-systemd"

# Toolchain
BINUTILS_VERSION="2.47"
GCC_VERSION="16.2.0"
GLIBC_VERSION="2.44"
LINUX_VERSION="7.1.8"

# Ferramentas temporarias
M4_VERSION="1.4.21"
NCURSES_VERSION="6.6"
BASH_VERSION="5.3"
COREUTILS_VERSION="9.11"
DIFFUTILS_VERSION="3.12"
FILE_VERSION="5.48"
FINDUTILS_VERSION="4.11.0"
GAWK_VERSION="5.4.1"
GREP_VERSION="3.12"
GZIP_VERSION="1.14"
MAKE_VERSION="4.4.1"
PATCH_VERSION="2.8"
SED_VERSION="4.10"
TAR_VERSION="1.35"
XZ_VERSION="5.8.3"

# Arquitetura
TARGET_ARCH="x86_64"