PROJECT_NAME="EclipseNova OS"
PROJECT_ID="eclipsenova"
PROJECT_VERSION="0.1"
PROJECT_CODENAME="nova"
ARCH="x86_64"
LFS_VERSION="13.1-systemd"
BLFS_VERSION="13.1-systemd"
BUILD_JOBS="${BUILD_JOBS:-1}"
