# ==========================================
# SolarNexum OS - System Configuration
# ==========================================

NAME="SolarNexum OS"
ID="solarnexum"
VERSION="0.1"
CODENAME="Genesis"

# Arquitetura
ARCH="x86_64"
KERNEL="linux"
LIBC="glibc"
INIT="systemd"

# Base
BASE="independent"
BUILD_METHOD="LFS"

# Objetivos
PERFORMANCE="optimized"
STABILITY="high"
SECURITY="high"
COMPATIBILITY="high"

# Interface futura
DESKTOP="xfce"

# Segurança
FIREWALL="nftables"
APPARMOR="enabled"
ANTIVIRUS="clamav"
SECURITY_UPDATES="automatic"

# Primeira máquina alvo
TARGET="Lenovo IdeaPad S145-15IIL"