# ==========================================
# SolarNexum OS - System Configuration
# ==========================================

NAME="SolarNexum OS"
VERSION="0.1"
CODENAME="Genesis"

# Base
BASE="Debian"
ARCH="amd64"

# Objetivos
PERFORMANCE="optimized"
STABILITY="high"
SECURITY="high"

# Interface
DESKTOP="xfce"

# Segurança
FIREWALL="nftables"
APPARMOR="enabled"
ANTIVIRUS="clamav"
SECURITY_UPDATES="automatic"

# Projeto
EDITION="Lenovo S145"
